;; -*- mode: lisp -*-
(source gnu)
(source melpa)

(depends-on "cask")

(depends-on "darkokai-theme")

(depends-on "magit")
(depends-on "avy")
(depends-on "multiple-cursors")
(depends-on "flycheck")
(depends-on "sr-speedbar")
(depends-on "zygospore")
(depends-on "editorconfig")
(depends-on "git-gutter-fringe")
(depends-on "anzu")
(depends-on "highlight-parentheses")
(depends-on "company")
(depends-on "git-timemachine")

(depends-on "ag")
(depends-on "ace-pinyin")
(depends-on "ace-mc")
(depends-on "projectile")
(depends-on "counsel")
(depends-on "counsel-projectile")
(depends-on "ivy")
(depends-on "swiper")
(depends-on "fasd")
(depends-on "direx")
(depends-on "dired-k")
(depends-on "undo-tree")

(depends-on "web-mode")
(depends-on "lua-mode")
(depends-on "elm-mode")
(depends-on "erlang")
(depends-on "elixir-mode")
(depends-on "alchemist")
(depends-on "ob-elixir")
(depends-on "markdown-mode")
(depends-on "polymode")
(depends-on "company-jedi")
(depends-on "restclient")
(depends-on "company-restclient")
